[package]
name = "lexsol"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/lexsol"
description = "Lexsol crate"

[features]
default = ["std", "evm", "yul", "solidity"]
alloc = ["tokit/alloc"]
std = ["tokit/std"]

yul = []
solidity = []
evm = []

bytes = ["dep:bytes", "tokit/bytes"]
hipstr = ["dep:hipstr", "tokit/hipstr"]
rowan = ["dep:rowan", "tokit/rowan"]

[dependencies]
tokit.workspace = true
paste.workspace = true
thiserror.workspace = true
derive_more.workspace = true

bytes = { workspace = true, optional = true }
hipstr = { workspace = true, optional = true }
rowan = { workspace = true, optional = true }

[lints]
workspace = true
